version: '3'
services:
  app:
    image: licencias-medicas-app
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@qxl9p21826dzwm8e_tp?TNS_ADMIN=/app/wallet
      - SPRING_DATASOURCE_USERNAME=FS1_LIC
      - SPRING_DATASOURCE_PASSWORD=RamoFullStack#1
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=oracle.jdbc.driver.OracleDriver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
      - SPRING_JPA_SHOW_SQL=true
      - TNS_ADMIN=/app/wallet
    networks:
      - default

networks:
  default:
    driver: bridge